# Generated by Django 4.1.6 on 2023-03-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=255)),
                ('doj', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('empphoto', models.FileField(upload_to='empphoto')),
            ],
        ),
        migrations.CreateModel(
            name='Myupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('myfiles', models.FileField(upload_to='myimages')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=15)),
                ('slug', models.CharField(max_length=150)),
                ('postimg', models.ImageField(upload_to='postimages')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
